version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps: 
      - run: echo "build"  
  deploy:
    docker:
      - image: circleci/python:latest
    steps: 
      - run: echo "deploy"

workflows:
  version: 2

  stage_workflow:
jobs:
  build:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: echo "build"
  test:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: echo "test"
workflows:
  build_and_test:
    jobs:
      - build
      - test   
   