version: 2
jobs:
  jobs:
  build:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
    build_and_deploy:
      jobs:
        - build
        - deploy

